[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
sol_test_users = "7vwrU2qgvtHuWgXsSyzfH8iBzztHpKbe2gVDXz18aNUR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kenchan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
